version: '3'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpwd
      POSTGRES_DB: dbdb
    volumes:
      - ./files/sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./files/sql/dml.sql:/docker-entrypoint-initdb.d/dml.sql