version: '3'
services:
    redis:
        image: redis:5
        restart: unless-stopped
        ports:
          - "6379:6379"
        command:
          - /bin/sh
          - -c
          - |
              nohup redis-server &
              sleep 3

              echo "adding some default key value"
              redis-cli SETEX samplekey_1 99999 value_100
              
              tail -f /dev/null
